package com.example.demo.domain.enums;

public enum CaseReviewStatus {
    NONE,
    REVIEW_REQUESTED,
    REVIEW_ASSIGNED,
    REVIEW_COMPLETED,
    REPORT_APPROVED,
    REVIEW_SUPPLEMENT_REQUESTED,
    SUPPLEMENT_REQUESTED,
    REVIEW_REVISION_REQUESTED,
    REVISION_REQUESTED,
    REVIEW_NEEDS_CHANGES
}
