-- =============================================================================
-- ForenShield AI — ERD v3 H2 DDL (로컬 개발용)
-- Reference: backend/docs/database/erd.md
-- H2 URL: jdbc:h2:file:./data/demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
--
-- JPA ddl-auto: update 가 엔티티 기준으로 테이블을 생성/갱신합니다.
-- 이 파일은 스키마 참조 및 수동 초기화용입니다.
-- =============================================================================

DROP TABLE IF EXISTS evidence;

-- 1. users
CREATE TABLE IF NOT EXISTS users (
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id            VARCHAR(100)  NOT NULL,
    email               VARCHAR(255)  NOT NULL,
    password            VARCHAR(255)  NOT NULL,
    name                VARCHAR(100)  NOT NULL,
    phone               VARCHAR(30),
    organization_type   VARCHAR(30)   NOT NULL,
    department          VARCHAR(255)  NOT NULL,
    position            VARCHAR(255),
    role                VARCHAR(20)   NOT NULL DEFAULT 'ROLE_USER',
    status              VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    dark_mode           BOOLEAN       NOT NULL DEFAULT FALSE,
    invite_code_id      BIGINT,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP,
    CONSTRAINT uq_users_login_id UNIQUE (login_id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

-- 2. invite_codes
CREATE TABLE IF NOT EXISTS invite_codes (
    invite_code_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(100)  NOT NULL,
    organization_type   VARCHAR(30)   NOT NULL,
    issued_by           BIGINT        NOT NULL REFERENCES users (user_id),
    status              VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    expires_at          TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at             TIMESTAMP,
    CONSTRAINT uq_invite_codes_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS idx_invite_codes_status ON invite_codes (status);
CREATE INDEX IF NOT EXISTS idx_invite_codes_issued_by ON invite_codes (issued_by);

ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_invite_code;
ALTER TABLE users ADD CONSTRAINT fk_users_invite_code
    FOREIGN KEY (invite_code_id) REFERENCES invite_codes (invite_code_id);

-- 3. evidences
CREATE TABLE IF NOT EXISTS evidences (
    evidence_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id             BIGINT        NOT NULL REFERENCES users (user_id),
    case_number             VARCHAR(100),
    case_name               VARCHAR(255),
    file_name               VARCHAR(500)  NOT NULL,
    file_type               VARCHAR(20)   NOT NULL,
    mime_type               VARCHAR(100)  NOT NULL,
    file_size               BIGINT        NOT NULL,
    hash_algorithm          VARCHAR(20)   NOT NULL DEFAULT 'SHA-256',
    original_hash_value     VARCHAR(64)   NOT NULL,
    original_storage_path   CLOB          NOT NULL,
    copy_hash_value         VARCHAR(64),
    copy_storage_path       CLOB,
    copy_status             VARCHAR(20)   NOT NULL DEFAULT 'NONE',
    copy_created_at         TIMESTAMP,
    copy_deleted_at         TIMESTAMP,
    status                  VARCHAR(20)   NOT NULL DEFAULT 'UPLOADED',
    uploaded_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_evidences_uploader_id ON evidences (uploader_id);
CREATE INDEX IF NOT EXISTS idx_evidences_case_number ON evidences (case_number);
CREATE INDEX IF NOT EXISTS idx_evidences_case_name ON evidences (case_name);
CREATE INDEX IF NOT EXISTS idx_evidences_original_hash ON evidences (original_hash_value);
CREATE INDEX IF NOT EXISTS idx_evidences_status ON evidences (status);

-- 4. evidence_metadata
CREATE TABLE IF NOT EXISTS evidence_metadata (
    metadata_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id         BIGINT        NOT NULL UNIQUE REFERENCES evidences (evidence_id) ON DELETE CASCADE,
    width               INTEGER,
    height              INTEGER,
    duration_sec        INTEGER,
    fps                 DOUBLE,
    codec               VARCHAR(100),
    sample_rate         INTEGER,
    channels            INTEGER,
    captured_at         TIMESTAMP,
    device_info         VARCHAR(500),
    exif_json           JSON,
    ffprobe_json        JSON,
    extraction_status   VARCHAR(20)   NOT NULL DEFAULT 'FAILED',
    extraction_error    CLOB,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. analysis_requests
CREATE TABLE IF NOT EXISTS analysis_requests (
    analysis_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_id         BIGINT        NOT NULL REFERENCES evidences (evidence_id),
    requested_by        BIGINT        NOT NULL REFERENCES users (user_id),
    status              VARCHAR(20)   NOT NULL DEFAULT 'QUEUED',
    requested_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP,
    error_code          VARCHAR(50),
    error_message       CLOB
);

CREATE INDEX IF NOT EXISTS idx_analysis_requests_evidence_id ON analysis_requests (evidence_id);
CREATE INDEX IF NOT EXISTS idx_analysis_requests_requested_by ON analysis_requests (requested_by);
CREATE INDEX IF NOT EXISTS idx_analysis_requests_status ON analysis_requests (status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_analysis_requests_one_completed
    ON analysis_requests (evidence_id)
    WHERE status = 'COMPLETED';

-- 6. analysis_results
CREATE TABLE IF NOT EXISTS analysis_results (
    analysis_result_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_request_id BIGINT        NOT NULL UNIQUE REFERENCES analysis_requests (analysis_request_id) ON DELETE CASCADE,
    risk_score          DOUBLE,
    confidence_score    DOUBLE,
    risk_level          VARCHAR(20),
    summary             CLOB,
    analyzed_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. analysis_module_results
CREATE TABLE IF NOT EXISTS analysis_module_results (
    module_result_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_result_id  BIGINT        NOT NULL REFERENCES analysis_results (analysis_result_id) ON DELETE CASCADE,
    file_type           VARCHAR(20),
    module_name         VARCHAR(100)  NOT NULL,
    detected            BOOLEAN,
    score               DOUBLE,
    confidence          DOUBLE,
    model_name          VARCHAR(100),
    model_version       VARCHAR(50),
    evidence_text       CLOB,
    details_json        JSON,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_analysis_module_results_analysis_result_id
    ON analysis_module_results (analysis_result_id);

-- 8. reports
CREATE TABLE IF NOT EXISTS reports (
    report_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_result_id  BIGINT        NOT NULL REFERENCES analysis_results (analysis_result_id),
    evidence_id         BIGINT        NOT NULL REFERENCES evidences (evidence_id),
    created_by          BIGINT        NOT NULL REFERENCES users (user_id),
    report_file_name    VARCHAR(500),
    storage_path        CLOB          NOT NULL,
    report_hash         VARCHAR(64),
    file_size           BIGINT,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reports_evidence_id ON reports (evidence_id);
CREATE INDEX IF NOT EXISTS idx_reports_analysis_result_id ON reports (analysis_result_id);
CREATE INDEX IF NOT EXISTS idx_reports_created_by ON reports (created_by);

-- 9. custody_logs
CREATE TABLE IF NOT EXISTS custody_logs (
    log_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id              BIGINT        NOT NULL REFERENCES users (user_id),
    target_type           VARCHAR(30)   NOT NULL,
    target_id             BIGINT        NOT NULL,
    action_type           VARCHAR(50)   NOT NULL,
    subject_hash          VARCHAR(64),
    storage_path_at_event CLOB,
    reason                CLOB,
    client_ip             VARCHAR(45),
    event_payload_json    JSON,
    previous_log_hash     VARCHAR(64),
    current_log_hash      VARCHAR(64)   NOT NULL,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_custody_logs_actor_id ON custody_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_custody_logs_target ON custody_logs (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_custody_logs_action_type ON custody_logs (action_type);
CREATE INDEX IF NOT EXISTS idx_custody_logs_created_at ON custody_logs (created_at);
