-- v2 사건 중심 증거 워크플로우 (FE case-workflow.ts)
-- 적용: psql ... -f 004_v2_case_evidence_workflow.postgresql.sql

ALTER TABLE evidences
    ADD COLUMN IF NOT EXISTS lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS evidence_role VARCHAR(20),
    ADD COLUMN IF NOT EXISTS display_label VARCHAR(100),
    ADD COLUMN IF NOT EXISTS replacement_evidence_id BIGINT REFERENCES evidences (evidence_id),
    ADD COLUMN IF NOT EXISTS excluded_reason VARCHAR(500);

ALTER TABLE evidences DROP CONSTRAINT IF EXISTS chk_evidences_lifecycle_status;
ALTER TABLE evidences ADD CONSTRAINT chk_evidences_lifecycle_status
    CHECK (lifecycle_status IN ('ACTIVE', 'EXCLUDED', 'REPLACED'));

ALTER TABLE evidences DROP CONSTRAINT IF EXISTS chk_evidences_evidence_role;
ALTER TABLE evidences ADD CONSTRAINT chk_evidences_evidence_role
    CHECK (evidence_role IS NULL OR evidence_role IN ('PRIMARY', 'SUPPLEMENT'));

CREATE TABLE IF NOT EXISTS case_profiles (
    case_profile_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id               BIGINT        NOT NULL,
    case_key                  VARCHAR(255)  NOT NULL,
    representative_evidence_id BIGINT       REFERENCES evidences (evidence_id),
    updated_at                TIMESTAMP(6)  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_case_profiles_uploader_case UNIQUE (uploader_id, case_key)
);

CREATE INDEX IF NOT EXISTS idx_case_profiles_uploader_id ON case_profiles (uploader_id);
