-- 로컬 H2는 ddl-auto=update로 자동 반영되지만 수동 초기화에도 사용합니다.
CREATE TABLE IF NOT EXISTS report_publication_snapshots (
    snapshot_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id               BIGINT NOT NULL,
    schema_version          VARCHAR(20) NOT NULL,
    pdf_template_version    VARCHAR(40) NOT NULL,
    report_input_json       CLOB NOT NULL,
    public_summary_json     CLOB NOT NULL,
    artifact_manifest_json  CLOB NOT NULL,
    display_policy_json     CLOB NOT NULL,
    snapshot_hash           VARCHAR(64) NOT NULL,
    created_at              TIMESTAMP NOT NULL,
    CONSTRAINT fk_report_publication_snapshots_report FOREIGN KEY (report_id) REFERENCES reports (report_id),
    CONSTRAINT ux_report_publication_snapshots_report UNIQUE (report_id)
);

CREATE INDEX IF NOT EXISTS idx_report_publication_snapshots_created_at
    ON report_publication_snapshots (created_at);
